version: 2
jobs:
  build-docker:
    docker:
      - image: docker:18.09.6
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Building image
          command: |
            docker build -t php-app -f docker/Dockerfile .
            docker images
workflows:
  version: 2
  build_and_release:
    jobs:
      - build-docker